name: flipperkit_sqflite_driver
description: flipperkit_sqflite_driver
version: 0.0.2
author: JianyingLi <lijy91@foxmail.com>
homepage: https://github.com/blankapp/flutter_flipperkit_plugins

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_flipperkit:
    git: https://github.com/warting/flutter_flipperkit.git
  sqflite: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
